### ISSUE TITLE
Не работает меню в Consta Header при использовании Layout

### ISSUE THREAD

**Issue by p1uton** [consta-design-system/header#30]
В Consta Header при создании кастомной шапки с помощью Layout не работает элемент Menu.
Воспроизводится на сайте Consta Header - https://header.consta.design/?path=/story/components-layout--playground
Воспроизводится в браузерах Chrome, Firefox, Opera
![2](https://user-images.githubusercontent.com/4601747/189886471-e23ae08e-8c1a-4ca6-9bfa-3f41750873a4.png)
![3](https://user-images.githubusercontent.com/4601747/189886487-4d7b1d4c-03ef-400d-a49a-03c34eb5982f.png)

**Comment by gizeasy** [comment]
Накинь на меню стили `width: 100%`
