### ISSUE TITLE
Зависает определение типов при использовании Header 

### ISSUE THREAD

**Issue by vpmew** [consta-design-system/header#39]
**"@consta/header": "^1.0.1"**
При подключении компонента  Header по всей IDE зависает определение типов на длительное время.

![photo_2023-01-26_12-19-09](https://user-images.githubusercontent.com/24278023/214778397-6238f76a-e140-4bbe-884e-1c3f55ff6a89.jpg)

**Comment by veselov-as** [comment]
Тоже столкнулись с этой ошибкой

 @vpmew получилось как-нибудь решить / исправить ?
